<?php
//000000000060a:41:{s:2:"id";s:2:"61";s:6:"header";s:42:"天津联合创业投资担保有限公司";s:4:"type";s:1:"1";s:4:"name";s:42:"天津联合创业投资担保有限公司";s:7:"user_id";s:7:"4437759";s:14:"agency_user_id";s:4:"3895";s:5:"brief";s:942:"天津联合创业投资担保有限公司是一家按照现代化企业制度要求建立的，完全市场化、专业化运作的担保机构，于2008年5月成立，注册资本一亿元人民币。2009年12月通过了ISO9001质量管理体系认证，公司已经与多家大型国有银行、股份制商业银行、地方性城商行及外资银行建立了授信合作关系，其风险识别能力与控制能力得到了金融界的认可。并与地方政府、社会组织、园区管委会、中介机构、同业机构、商协会等建立了战略联盟。发挥集团多业务平台及产品研发的优势，通过多种渠道、多种方式满足不同客户的资金需求，实现各类资源的合理分配。随着业务经验的积累、本地市场的熟悉，依托集团丰富的风险控制经验，天津联合创业投资担保有限公司必将为更多的中小企业提供及时的、更好的金融服务。";s:13:"company_brief";s:942:"天津联合创业投资担保有限公司是一家按照现代化企业制度要求建立的，完全市场化、专业化运作的担保机构，于2008年5月成立，注册资本一亿元人民币。2009年12月通过了ISO9001质量管理体系认证，公司已经与多家大型国有银行、股份制商业银行、地方性城商行及外资银行建立了授信合作关系，其风险识别能力与控制能力得到了金融界的认可。并与地方政府、社会组织、园区管委会、中介机构、同业机构、商协会等建立了战略联盟。发挥集团多业务平台及产品研发的优势，通过多种渠道、多种方式满足不同客户的资金需求，实现各类资源的合理分配。随着业务经验的积累、本地市场的熟悉，依托集团丰富的风险控制经验，天津联合创业投资担保有限公司必将为更多的中小企业提供及时的、更好的金融服务。";s:7:"history";s:0:"";s:7:"content";s:0:"";s:9:"is_effect";s:1:"1";s:11:"create_time";s:1:"0";s:11:"update_time";s:1:"0";s:4:"sort";s:1:"0";s:10:"short_name";s:50:"天津联合创业投资担保（担保/代偿I）";s:7:"address";s:60:"天津市河西区解放南路龙海公寓10号楼2门底商";s:8:"realname";s:6:"高雁";s:6:"mobile";s:0:"";s:8:"postcode";s:0:"";s:3:"fax";s:0:"";s:5:"email";s:0:"";s:6:"review";s:4:"0.00";s:7:"premium";s:4:"0.00";s:13:"caution_money";s:4:"0.00";s:9:"agreement";s:0:"";s:8:"bankzone";s:42:"大连银行股份有限公司天津分行";s:8:"bankcard";s:15:"147200209002226";s:9:"mechanism";s:2770:"<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">借款人出现逾期、坏账和不还钱怎么办？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p style="font-size:12px;font-weight:normal;line-height:18px;" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="">如果借款人出现逾期或坏账，对该借贷行为担保的担保机构对每笔借款提供不可撤销的全额本息担保，贷款到期后，借款人出现任何问题，担保机构即会启动代偿机制，按照《保证合同》约定向投资人偿付所有剩余本金及利息。然后担保机构自行负责之后的追偿，催收工作。投资者不会承担合同约定以外的任何损失，安全无风险。</p>
</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">平台如果不存在了，投资者的收益如何保障？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p style="font-size:12px;font-weight:normal;line-height:18px;" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="">作为信息中介平台，主要职能是交易撮合，即使平台不存在，投资者的收益也还是有足够保障的。</p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="">首先投融双方的债权债务关系不会消失；</p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="">其次担保公司会负责投资人的全额本息担保；</p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="">最后独立于平台外的第三方支付平台有通路保证还本付息的资金会在项目到期日划转到投资人之前在平台上绑定的收款银行卡中。</p>
</h3>
";s:7:"license";s:15:"120103000083732";s:18:"repay_inform_email";s:0:"";s:6:"is_icp";s:1:"0";s:7:"site_id";s:1:"0";s:20:"business_place_state";s:0:"";s:12:"risk_control";s:0:"";s:12:"agency_brief";s:0:"";s:11:"man_product";s:0:"";s:10:"team_brief";s:0:"";s:18:"future_expectation";s:0:"";s:17:"is_credit_display";s:1:"1";s:27:"exchange_repay_notice_email";s:0:"";s:25:"exchange_repay_plan_email";s:0:"";}
?>