<?php
//000000000060a:41:{s:2:"id";s:3:"193";s:6:"header";s:42:"深圳美福珠宝饰品投资有限公司";s:4:"type";s:1:"1";s:4:"name";s:42:"深圳美福珠宝饰品投资有限公司";s:7:"user_id";s:7:"6583805";s:14:"agency_user_id";s:7:"3448885";s:5:"brief";s:492:"深圳美福珠宝饰品投资有限公司主要经营对黄金业的投资及管理；黄金市场交易信息咨询；贵金属、金银首饰等批发、零售、保管及租赁。公司团队具有丰富的行业经验，拥有实力雄厚的合作伙伴和优质的经营项目。公司以诚信、共赢、开创经营理念，创造良好的企业环境，以全新的管理模式，完善的技术，周到的服务，卓越的品质为生存根本，实现了快速成长和发展。";s:13:"company_brief";s:492:"深圳美福珠宝饰品投资有限公司主要经营对黄金业的投资及管理；黄金市场交易信息咨询；贵金属、金银首饰等批发、零售、保管及租赁。公司团队具有丰富的行业经验，拥有实力雄厚的合作伙伴和优质的经营项目。公司以诚信、共赢、开创经营理念，创造良好的企业环境，以全新的管理模式，完善的技术，周到的服务，卓越的品质为生存根本，实现了快速成长和发展。";s:7:"history";s:0:"";s:7:"content";s:0:"";s:9:"is_effect";s:1:"1";s:11:"create_time";s:1:"0";s:11:"update_time";s:1:"0";s:4:"sort";s:1:"0";s:10:"short_name";s:32:"美福珠宝（担保/代偿I）";s:7:"address";s:71:"深圳市罗湖区笋岗街道田贝一路23号文锦广场文盛中心";s:8:"realname";s:6:"王成";s:6:"mobile";s:0:"";s:8:"postcode";s:0:"";s:3:"fax";s:0:"";s:5:"email";s:0:"";s:6:"review";s:4:"0.00";s:7:"premium";s:4:"0.00";s:13:"caution_money";s:4:"0.00";s:9:"agreement";s:0:"";s:8:"bankzone";s:48:"海口联合农村商业银行股份有限公司";s:8:"bankcard";s:19:"8981214000000005163";s:9:"mechanism";s:2770:"<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">借款人出现逾期、坏账和不还钱怎么办？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">如果借款人出现逾期或坏账，对该借贷行为担保的担保机构对每笔借款提供不可撤销的全额本息担保，贷款到期后，借款人出现任何问题，担保机构即会启动代偿机制，按照《保证合同》约定向投资人偿付所有剩余本金及利息。然后担保机构自行负责之后的追偿，催收工作。投资者不会承担合同约定以外的任何损失，安全无风险。</p>
</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">平台如果不存在了，投资者的收益如何保障？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">作为信息中介平台，主要职能是交易撮合，即使平台不存在，投资者的收益也还是有足够保障的。</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">首先投融双方的债权债务关系不会消失；</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">其次担保公司会负责投资人的全额本息担保；</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">最后独立于平台外的第三方支付平台有通路保证还本付息的资金会在项目到期日划转到投资人之前在平台上绑定的收款银行卡中。</p>
</h3>
";s:7:"license";s:15:"440301111425844";s:18:"repay_inform_email";s:0:"";s:6:"is_icp";s:1:"0";s:7:"site_id";s:1:"0";s:20:"business_place_state";s:0:"";s:12:"risk_control";s:0:"";s:12:"agency_brief";s:0:"";s:11:"man_product";s:0:"";s:10:"team_brief";s:0:"";s:18:"future_expectation";s:0:"";s:17:"is_credit_display";s:1:"1";s:27:"exchange_repay_notice_email";s:0:"";s:25:"exchange_repay_plan_email";s:0:"";}
?>