<?php
//000000000060a:41:{s:2:"id";s:3:"191";s:6:"header";s:36:"深圳元昌珠宝饰品有限公司";s:4:"type";s:1:"1";s:4:"name";s:36:"深圳元昌珠宝饰品有限公司";s:7:"user_id";s:7:"6572222";s:14:"agency_user_id";s:7:"7844451";s:5:"brief";s:700:"深圳元昌珠宝饰品有限公司的主要业务定位于黄金财富管理系统服务商，面向银行、第三方渠道和黄金消费者，创新提出并持续打造“实物贵金属产业链运营系统”，为中国家庭和企业家创造性地提供一揽子的黄金储备产品与服务。公司曾开发了中国熊猫金银纪念币产品线、实物贵金属题材产品线、机构黄金租赁业务和个人黄金储备等业务。公司成功运作了2012年伦敦奥运金项目。公司主要针对深圳黄金珠宝企业聚集的产业特征，积极拓展企业黄金租赁业务，通过对接黄金产业链上下游，为黄金珠宝企业提供金融支持和服务。";s:13:"company_brief";s:700:"深圳元昌珠宝饰品有限公司的主要业务定位于黄金财富管理系统服务商，面向银行、第三方渠道和黄金消费者，创新提出并持续打造“实物贵金属产业链运营系统”，为中国家庭和企业家创造性地提供一揽子的黄金储备产品与服务。公司曾开发了中国熊猫金银纪念币产品线、实物贵金属题材产品线、机构黄金租赁业务和个人黄金储备等业务。公司成功运作了2012年伦敦奥运金项目。公司主要针对深圳黄金珠宝企业聚集的产业特征，积极拓展企业黄金租赁业务，通过对接黄金产业链上下游，为黄金珠宝企业提供金融支持和服务。";s:7:"history";s:0:"";s:7:"content";s:0:"";s:9:"is_effect";s:1:"1";s:11:"create_time";s:1:"0";s:11:"update_time";s:1:"0";s:4:"sort";s:1:"0";s:10:"short_name";s:38:"深圳元昌珠宝（担保/代偿I）";s:7:"address";s:118:"深圳市前海深港合作区前湾一路鲤鱼门街一号前海深港合作区管理局综合办公室楼A楼201室";s:8:"realname";s:9:"任冬宁";s:6:"mobile";s:0:"";s:8:"postcode";s:0:"";s:3:"fax";s:0:"";s:5:"email";s:0:"";s:6:"review";s:4:"0.00";s:7:"premium";s:4:"0.00";s:13:"caution_money";s:4:"0.00";s:9:"agreement";s:0:"";s:8:"bankzone";s:54:"中国建设银行股份有限公司深圳南新支行";s:8:"bankcard";s:20:"44201017100052506617";s:9:"mechanism";s:2770:"<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">借款人出现逾期、坏账和不还钱怎么办？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">如果借款人出现逾期或坏账，对该借贷行为担保的担保机构对每笔借款提供不可撤销的全额本息担保，贷款到期后，借款人出现任何问题，担保机构即会启动代偿机制，按照《保证合同》约定向投资人偿付所有剩余本金及利息。然后担保机构自行负责之后的追偿，催收工作。投资者不会承担合同约定以外的任何损失，安全无风险。</p>
</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px="">平台如果不存在了，投资者的收益如何保障？</h3>
<h3 class="yellwo" normal;?="" 16px;="" sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 67);="" 137,="" rgb(244,="" 0px;="" 0px="" 20px=""><p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">作为信息中介平台，主要职能是交易撮合，即使平台不存在，投资者的收益也还是有足够保障的。</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">首先投融双方的债权债务关系不会消失；</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">其次担保公司会负责投资人的全额本息担保；</p>
<p sans-serif;="" arial,="" helvetica,="" neue?,="" ?helvetica="" yahei?,="" ?microsoft="" 0px;="" 0px;?="" 14px;="" 135);="" 135,="" rgb(135,="" style="font-size:12px;font-weight:normal;line-height:18px;">最后独立于平台外的第三方支付平台有通路保证还本付息的资金会在项目到期日划转到投资人之前在平台上绑定的收款银行卡中。</p>
</h3>
";s:7:"license";s:18:"91440300057851498F";s:18:"repay_inform_email";s:0:"";s:6:"is_icp";s:1:"0";s:7:"site_id";s:1:"0";s:20:"business_place_state";s:0:"";s:12:"risk_control";s:0:"";s:12:"agency_brief";s:0:"";s:11:"man_product";s:0:"";s:10:"team_brief";s:0:"";s:18:"future_expectation";s:0:"";s:17:"is_credit_display";s:1:"1";s:27:"exchange_repay_notice_email";s:0:"";s:25:"exchange_repay_plan_email";s:0:"";}
?>