<?php
//000000000060a:41:{s:2:"id";s:1:"5";s:6:"header";s:154:"<b><span style="font-size:18px;">北京</span></b><font size="4"><span style="line-height:27px;"><b>联合开元融资担保有限公司</b></span></font>";s:4:"type";s:1:"1";s:4:"name";s:42:"北京联合开元融资担保有限公司";s:7:"user_id";s:4:"4165";s:14:"agency_user_id";s:4:"4282";s:5:"brief";s:1824:"北京联合开元融资担保有限公司（下称“公司”）是联合创业担保集团有限公司在北京投资设立的控股子公司，是集团为进一步巩固在环渤海地区竞争优势、拓展北京及周边市场的重要基地。公司注册资金人民币3亿元，为北京市信用担保业协会常务理事单位。主营中小企业融资担保，履约担保及投资管理，投资咨询等。公司成立以来，集团先后派驻了多名高管及担保业务骨干，并从北京当地人才选聘了一批具有金融、经济、会计、法律专业背景和从业经验的专业人才。公司根据集团的业务规划，在集团指导下建立了完整的市场开发、业务操作、风险控制、资产管理等运作体系，储备了一批优质客户资源。公司将通过与政府、银行及其他相关机构建立密切合作关系，为北京及周边地区的中小企业提供优质的金融服务。

公司目前与国家开发银行、农业发展银行、农业银行、建设银行、交通银行、招商银行、广发银行、浦发银行、天津银行、北京银行等十余家银行建立授信合作关系，截止2013年10月31日，取得授信总额10亿元。
中国的中小企业超过4000万家，占中国企业总数的89%。大多数中小企业都存在不同程度的融资问题，集团针对中小企业的融资难题，提供多样化的融资服务，具有卓越的创新能力和巨大的发展潜力。
从成立至今，集团公司累计担保额超过121亿元，为10,000多户企业及个人客户提供了融资服务，位于全国担保行业前列。累计支持企业从业人数10余万人，协助企业累计实现销售收入约400亿元，实现利润近50亿元，为地方经济发展做出了卓越的贡献。";s:13:"company_brief";s:1826:"北京联合开元融资担保有限公司（下称“公司”）是联合创业担保集团有限公司在北京投资设立的控股子公司，是集团为进一步巩固在环渤海地区竞争优势、拓展北京及周边市场的重要基地。公司注册资金人民币3亿元，为北京市信用担保业协会常务理事单位。主营中小企业融资担保，履约担保及投资管理，投资咨询等。公司成立以来，集团先后派驻了多名高管及担保业务骨干，并从北京当地人才选聘了一批具有金融、经济、会计、法律专业背景和从业经验的专业人才。公司根据集团的业务规划，在集团指导下建立了完整的市场开发、业务操作、风险控制、资产管理等运作体系，储备了一批优质客户资源。公司将通过与政府、银行及其他相关机构建立密切合作关系，为北京及周边地区的中小企业提供优质的金融服务。

公司目前与国家开发银行、农业发展银行、农业银行、建设银行、交通银行、招商银行、广发银行、浦发银行、天津银行、北京银行等十余家银行建立授信合作关系，截止2013年10月31日，取得授信总额10亿元。
中国的中小企业超过4000万家，占中国企业总数的89%。大多数中小企业都存在不同程度的融资问题，集团针对中小企业的融资难题，提供多样化的融资服务，具有卓越的创新能力和巨大的发展潜力。
从成立至今，集团公司累计担保额超过121亿元，为10,000多户企业及个人客户提供了融资服务，位于全国担保行业前列。累计支持企业从业人数10余万人，协助企业累计实现销售收入约400亿元，实现利润近50亿元，为地方经济发展做出了卓越的贡献。
";s:7:"history";s:1164:"<p class="MsoNormal" align="left"><span style="font-size:11pt;font-family:仿宋;">公司前身为联合创业担保集团有限公司北京分公司，于<st1 :chsdate="" year="2005" day="28" islunardate="False" isrocdate="False" w:st="on" month="11"><span lang="EN-US">2005</span>年<span lang="EN-US">11</span>月<span lang="EN-US">28</span>日</st1>在北京设立，配合总公司开展在北京及周边地区业务运作的前期调研以及相关准备工作，<st1 :chsdate="" year="2009" day="7" islunardate="False" isrocdate="False" w:st="on" month="1"><span lang="EN-US">2009</span>年<span lang="EN-US">1</span>月<span lang="EN-US">7</span>日</st1>在北京市工商行政管理局正式注册登记，注册资本金<span lang="EN-US">3</span>亿元人民币，实收资本<span lang="EN-US">3</span>亿元，全部为货币资金方式。<span lang="EN-US">2010</span>年<span lang="EN-US">11</span>月<span lang="EN-US">17</span>日公司章程修订，联合创业担保集团有限公司股权比例从<span lang="EN-US">99.67%</span>调整到<span lang="EN-US">100%</span>，公司成为联合创业担保集团独资子公司。</span></p>
";s:7:"content";s:0:"";s:9:"is_effect";s:1:"1";s:11:"create_time";s:1:"0";s:11:"update_time";s:1:"0";s:4:"sort";s:1:"0";s:10:"short_name";s:32:"开元担保（担保/代偿I）";s:7:"address";s:60:"北京市西城区金融街7号英蓝国际金融中心5F516";s:8:"realname";s:9:"韩光磊";s:6:"mobile";s:12:"010-58369167";s:8:"postcode";s:6:"100033";s:3:"fax";s:12:"010-58369167";s:5:"email";s:0:"";s:6:"review";s:5:"10.00";s:7:"premium";s:5:"10.00";s:13:"caution_money";s:5:"10.00";s:9:"agreement";s:0:"";s:8:"bankzone";s:0:"";s:8:"bankcard";s:0:"";s:9:"mechanism";s:2955:"<h3 class="yellwo" 20px="" 0px="" 0px;="" rgb(244,="" 137,="" 67);="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" 16px;="" normal;?="">借款人出现逾期、坏账和不还钱怎么办？</h3>
<h3 class="yellwo" 20px="" 0px="" 0px;="" rgb(244,="" 137,="" 67);="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" 16px;="" normal;?=""><p style="font-size:12px;font-weight:normal;line-height:18px;" 0px;="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" rgb(135,="" 135,="" 135);="" 14px;="" 0px;?=""><span style="font-size:14px;">如果借款人出现逾期或坏账，对该借贷行为担保的担保机构对每笔借款提供不可撤销的全额本息担保，贷款到期后，借款人出现任何问题，担保机构即会启动代偿机制，按照《保证合同》约定向投资人偿付所有剩余本金及利息。然后担保机构自行负责之后的追偿，催收工作。投资者不会承担合同约定以外的任何损失，安全无风险。</span></p>
</h3>
<h3 class="yellwo" 20px="" 0px="" 0px;="" rgb(244,="" 137,="" 67);="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" 16px;="" normal;?="">平台如果不存在了，投资者的收益如何保障？</h3>
<h3 class="yellwo" 20px="" 0px="" 0px;="" rgb(244,="" 137,="" 67);="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" 16px;="" normal;?=""><p style="font-size:12px;font-weight:normal;line-height:18px;" 0px;="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" rgb(135,="" 135,="" 135);="" 14px;="" 0px;?=""><span style="font-size:14px;">作为信息中介平台，主要职能是交易撮合，即使平台不存在，投资者的收益也还是有足够保障的。</span></p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" 0px;="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" rgb(135,="" 135,="" 135);="" 14px;="" 0px;?=""><span style="font-size:14px;">首先投融双方的债权债务关系不会消失；</span></p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" 0px;="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" rgb(135,="" 135,="" 135);="" 14px;="" 0px;?=""><span style="font-size:14px;">其次担保公司会负责投资人的全额本息担保；</span></p>
<p style="font-size:12px;font-weight:normal;line-height:18px;" 0px;="" ?microsoft="" yahei?,="" ?helvetica="" neue?,="" helvetica,="" arial,="" sans-serif;="" rgb(135,="" 135,="" 135);="" 14px;="" 0px;?=""><span style="font-size:14px;">最后独立于平台外的第三方支付平台有通路保证还本付息的资金会在项目到期日划转到投资人之前在平台上绑定的收款银行卡中。</span></p>
</h3>
";s:7:"license";s:18:"911100006835540799";s:18:"repay_inform_email";s:0:"";s:6:"is_icp";s:1:"0";s:7:"site_id";s:1:"0";s:20:"business_place_state";s:0:"";s:12:"risk_control";s:0:"";s:12:"agency_brief";s:0:"";s:11:"man_product";s:0:"";s:10:"team_brief";s:0:"";s:18:"future_expectation";s:0:"";s:17:"is_credit_display";s:1:"1";s:27:"exchange_repay_notice_email";s:0:"";s:25:"exchange_repay_plan_email";s:0:"";}
?>